name: "Setup Poetry"
author: "Rodolfo Puig <rodolfo@puig.io>"
description: "Installs and configures Poetry"
branding:
  color: "gray-dark"
  icon: "package"
inputs:
  poetry-version:
    description: "Poetry version to install"
    required: false
    default: ""
outputs:
  poetry-binary:
    description: "Poetry binary path"
    value: ${{ steps.poetry-installer.outputs.executable }}
  poetry-version:
    description: "Poetry version"
    value: ${{ steps.poetry-installer.outputs.version }}
runs:
  using: composite
  steps:
    - id: poetry-installer
      run: |
        ${GITHUB_ACTION_PATH}/scripts/install-poetry-wrapper.sh \
          "${{ runner.os }}" \
          "${{ inputs.poetry-version }}"
      shell: bash
