name: "Setup Poetry"
author: "Rodolfo Puig <rodolfo@puig.io>"
description: "Installs and configures Poetry"
branding:
  color: "gray-dark"
  icon: "package"
inputs:
  poetry-version:
    description: "Poetry version to Installs"
    required: false
    default: ""
  cache-dir:
    description: "Poetry cache directory"
    required: false
    default: ""
  virtualenvs-create:
    description: "Whether Poetry should create a virtualenv or not"
    required: false
    default: "false"
  virtualenvs-in-project:
    description: "Whether Poetry should create a virtualenv directory in the project directory or not"
    required: false
    default: "true"
  virtualenvs-path:
    description: "Poetry virtualenv path"
    required: false
    default: "{cache-dir}/virtualenvs"
outputs:
  poetry-path:
    description: "Poetry bin directory"
    value: ${{ steps.poetry-metadata.outputs.os-type }}
runs:
  using: composite
  steps:
    - id: poetry-installer
      run: |
        ${{ github.action_path }}/install-poetry-wrapper.sh \
          "${{ runner.os }}" \
          "${{ inputs.poetry-version }}"
      shell: bash
    - id: poetry-metadata
      run: |
        case "${{ runner.os }}" in
          win*) echo "::set-output name=bin-dir::$APPDATA/Python/Scripts" ;;
          *)    echo "::set-output name=bin-dir::$HOME/.local/bin" ;;
        esac
      shell: bash
